// Copyright 2026 aclee555. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"github.com/aclee555/find-me-gluten-free-pp-cli/internal/cli"
	"github.com/aclee555/find-me-gluten-free-pp-cli/internal/client"
	"github.com/aclee555/find-me-gluten-free-pp-cli/internal/config"
	"github.com/aclee555/find-me-gluten-free-pp-cli/internal/mcp/cobratree"
	"github.com/aclee555/find-me-gluten-free-pp-cli/internal/store"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("chains_list",
			mcplib.WithDescription("List chain restaurants with gluten-free options. Returns array of html_link."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/chains", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("cities_list",
			mcplib.WithDescription("List cities in a state or region (e.g., /us/va lists Virginia cities). Required: country, state. Returns array of html_link."),
			mcplib.WithString("country", mcplib.Required(), mcplib.Description("Country code (us, gb, ...).")),
			mcplib.WithString("state", mcplib.Required(), mcplib.Description("State or region code (va, ca, on, ...).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/{country}/{state}", []mcpParamBinding{{PublicName: "country", WireName: "country", Location: "path"},{PublicName: "state", WireName: "state", Location: "path"}, }, []string{"country","state", }),
	)
	s.AddTool(
		mcplib.NewTool("cities_ranked",
			mcplib.WithDescription("Find Me Gluten Free's published ranking of the most gluten-free-friendly cities. Returns array of html_link."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/most-gluten-free-friendly-cities", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("countries_list",
			mcplib.WithDescription("List every country with gluten-free coverage on Find Me Gluten Free. Returns array of html_link."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/countries", []mcpParamBinding{ }, []string{ }),
	)
	s.AddTool(
		mcplib.NewTool("places_filter",
			mcplib.WithDescription("List restaurants in a city filtered by cuisine or feature. The filter slug can be 'dedicated-facilities', 'gluten-free-menu', or any of 200+ cuisine slugs (burgers, pizza, bakeries, ...). Required: country, state, city, filter. Returns array of html_link."),
			mcplib.WithString("country", mcplib.Required(), mcplib.Description("Country code.")),
			mcplib.WithString("state", mcplib.Required(), mcplib.Description("State or region code.")),
			mcplib.WithString("city", mcplib.Required(), mcplib.Description("City slug.")),
			mcplib.WithString("filter", mcplib.Required(), mcplib.Description("Filter slug: dedicated-facilities, gluten-free-menu, or a cuisine slug (burgers, pizza, bakeries, asian, breakfast,...")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/{country}/{state}/{city}/{filter}", []mcpParamBinding{{PublicName: "country", WireName: "country", Location: "path"},{PublicName: "state", WireName: "state", Location: "path"},{PublicName: "city", WireName: "city", Location: "path"},{PublicName: "filter", WireName: "filter", Location: "path"}, }, []string{"country","state","city","filter", }),
	)
	s.AddTool(
		mcplib.NewTool("places_get",
			mcplib.WithDescription("Get a single restaurant page. Use 'places hydrate' for the parsed schema.org JSON-LD (rating, reviews, lat/lng) — this raw command returns the title/description/canonical metadata only. Required: slug, biz_id."),
			mcplib.WithString("slug", mcplib.Required(), mcplib.Description("Restaurant slug from the URL (e.g., 'pinkys').")),
			mcplib.WithString("biz_id", mcplib.Required(), mcplib.Description("Restaurant numeric ID from the URL (e.g., 6118524171452416).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/biz/{slug}/{biz_id}", []mcpParamBinding{{PublicName: "slug", WireName: "slug", Location: "path"},{PublicName: "biz_id", WireName: "biz_id", Location: "path"}, }, []string{"slug","biz_id", }),
	)
	s.AddTool(
		mcplib.NewTool("places_list",
			mcplib.WithDescription("List restaurants in a city (e.g., /us/va/richmond). Required: country, state, city. Returns array of html_link."),
			mcplib.WithString("country", mcplib.Required(), mcplib.Description("Country code.")),
			mcplib.WithString("state", mcplib.Required(), mcplib.Description("State or region code.")),
			mcplib.WithString("city", mcplib.Required(), mcplib.Description("City slug (e.g., richmond).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/{country}/{state}/{city}", []mcpParamBinding{{PublicName: "country", WireName: "country", Location: "path"},{PublicName: "state", WireName: "state", Location: "path"},{PublicName: "city", WireName: "city", Location: "path"}, }, []string{"country","state","city", }),
	)
	s.AddTool(
		mcplib.NewTool("states_list",
			mcplib.WithDescription("List states or regions in a country (e.g., /us, /gb, /fr). Required: country. Returns array of html_link."),
			mcplib.WithString("country", mcplib.Required(), mcplib.Description("Two-letter country code (us, gb, fr, ie, ca).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/{country}", []mcpParamBinding{{PublicName: "country", WireName: "country", Location: "path"}, }, []string{"country", }),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'find-me-gluten-free-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'find-me-gluten-free-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "find-me-gluten-free-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "find-me-gluten-free-pp-cli", "data.db")
}
// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "find-me-gluten-free",
		"description": "Cache, compare, and diff Find Me Gluten Free cities from your terminal. Multi-city trip compare, lat/lng radius...",
		"archetype":   "generic",
		"tool_count":  8,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion find-me-gluten-free-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name": "chains",
				"description": "Chain restaurant index",
				"endpoints": []string{"list",  },
				"syncable": true,
			},
			{
				"name": "cities",
				"description": "City directory and rankings",
				"endpoints": []string{"list", "ranked",  },
				"syncable": true,
				"searchable": true,
			},
			{
				"name": "countries",
				"description": "Country directory",
				"endpoints": []string{"list",  },
				"syncable": true,
			},
			{
				"name": "places",
				"description": "Restaurants and the places-by-city / places-by-cuisine views",
				"endpoints": []string{"filter", "get", "list",  },
				"searchable": true,
			},
			{
				"name": "states",
				"description": "State / region directory under one country",
				"endpoints": []string{"list",  },
				"searchable": true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Multi-city trip compare", "command": "trip compare", "description": "Compare 2+ cities side-by-side: dedicated-GF count, GF-menu count, total places, average rating, and top-rated picks...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "City diff since last sync", "command": "cities diff", "description": "Show what changed in a city since the last time you synced it: added/removed places, rating drift, new low-star...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Lat/lng radius search", "command": "places near", "description": "Find dedicated-GF or GF-menu places within a radius of a lat/lng using Haversine over locally cached schema.org geo...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "City stats rollup", "command": "places stats", "description": "One-shot SQL aggregate over a city: count, average rating, p50/p90 rating, dedicated-GF percent, GF-menu percent....", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "City-wide recent reviews", "command": "reviews recent", "description": "Newest reviews across every place in a city, sorted by datePublished. Filter to safety-report-style 1-2 star reviews...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Watchlist with change report", "command": "watch", "description": "Watch specific places; periodic 'watch report' fetches each and reports rating drift and new low-rated reviews since...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Cuisine cross-city compare", "command": "cuisines compare", "description": "For one cuisine across multiple cities: per-city count, dedicated-GF percent, top-rated place. Useful when planning...", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Safety-report review filter", "command": "reviews safety", "description": "Filter cached reviews for one place to those mentioning got-glutened / cross-contamination keywords from a curated,...", "rationale": "", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Multi-city trip compare", "insight": ""},
			{"topic": "City diff since last sync", "insight": ""},
			{"topic": "Lat/lng radius search", "insight": ""},
			{"topic": "City stats rollup", "insight": ""},
			{"topic": "City-wide recent reviews", "insight": ""},
			{"topic": "Watchlist with change report", "insight": ""},
			{"topic": "Cuisine cross-city compare", "insight": ""},
			{"topic": "Safety-report review filter", "insight": ""},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
