// Copyright 2026 aclee555. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newCitiesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cities",
		Short: "City directory and rankings",
	}

	cmd.AddCommand(newCitiesListCmd(flags))
	cmd.AddCommand(newCitiesRankedCmd(flags))
	return cmd
}
