// Copyright 2026 aclee555. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newPlacesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "places",
		Short: "Restaurants and the places-by-city / places-by-cuisine views",
	}

	cmd.AddCommand(newPlacesFilterCmd(flags))
	cmd.AddCommand(newPlacesGetCmd(flags))
	cmd.AddCommand(newPlacesListCmd(flags))
	return cmd
}
