// Copyright 2026 aclee555. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newStatesPromotedCmd(flags *rootFlags) *cobra.Command {

	cmd := &cobra.Command{
		Use:   "states <country>",
		Short: "List states or regions in a country (e.g., /us, /gb, /fr).",
		Long:  "Shortcut for 'states list'. List states or regions in a country (e.g., /us, /gb, /fr).",
		Example: "  find-me-gluten-free-pp-cli states example-value",
		Annotations: map[string]string{"pp:endpoint": "states.list", "pp:method": "GET", "pp:path": "/{country}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/{country}"
			if len(args) < 1 {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "country is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "country"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("country is required\nUsage: %s <%s>", cmd.CommandPath(), "country"))
			}
			path = replacePathParam(path, "country", args[0])
			htmlRequestParams := map[string]string{}
			params := map[string]string{}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "states", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			if !flags.dryRun {
				data, err = extractHTMLResponse(data, htmlExtractionOptions{
					Mode: "links",
					BaseURL: htmlExtractionRequestURL(c.BaseURL, path, htmlRequestParams),
					LinkPrefixes: []string{
						"/",
					},
					Limit: 100,
					ScriptSelector: "script#__NEXT_DATA__",
					JSONPath: "",
				})
				if err != nil {
					return err
				}
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
